### PR TITLE
Add port number option to sftp config.

### PR DESCRIPTION
**Pull request by panshul007**

### CODE REVIEW

**Comment by panshul007** [comment]
@emmenko @hajoeichler please have a look... I need this urgently.

**Comment by hajoeichler** [comment]
Please provide a test or at least adjust an existing.

**Comment by emmenko** [comment]
:+1:

**Comment by panshul007** [comment]
@hajoeichler will do it in a separate issue: https://github.com/sphereio/sphere-node-utils/issues/12

**Pull request merged**
